apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.certificate.name}}
  namespace: {{.Values.certificate.namespace}}
spec:
  secretName: {{.Values.certificate.secretName}}
  issuerRef:
    kind: ClusterIssuer
    name: {{ required ".Values.certificate.clusterIssuerRefName is required" .Values.certificate.clusterIssuerRefName }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}