apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterIssuer.name}}
  namespace: {{.Values.clusterIssuer.namespace}}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ required ".Values.clusterIssuer.acme.email entry required!" .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{.Values.clusterIssuer.acme.privateKeySecretRefName}}
    solvers:
      - selector:
          dnsZones:
            {{- range .Values.clusterIssuer.selector.dnsZones }}
            - {{ . | quote }}
            {{- end }}
        dns01:
          route53:
            region: {{ .Values.clusterIssuer.selector.route53.region }}
            hostedZoneID: {{ .Values.clusterIssuer.selector.route53.hostedZoneID }}
            {{- if .Values.clusterIssuer.selector.route53.iamRole }}
            role: {{ .Values.clusterIssuer.selector.route53.iamRole }}
            {{ else }}
            {{- if .Values.clusterIssuer.selector.route53.accessKeyID }}
            accessKeyID: {{ .Values.clusterIssuer.selector.route53.accessKeyID }}
            secretAccessKeySecretRef:
              name: {{ .Values.clusterIssuer.selector.route53.secretAccessKeySecretRefName }}
              key: {{ .Values.clusterIssuer.selector.route53.secretAccessKeySecretRefValue }}
            {{- end -}}
            {{- end -}}

